### ISSUE TITLE
Does not crops when tried with screenshot images

### ISSUE THREAD

**Issue by MahalakshmiSruthi** [qchenqizhi/QCropper#5] opened 2021-01-20 11:21 UTC
Took and a screenshot and tried to crop with QCropper but returns the original image.

https://user-images.githubusercontent.com/74170265/105168113-a7ba3e00-5b3f-11eb-9a58-521679a327bb.mov

**Comment by qchenqizhi** [comment] 2021-03-10 02:44
Thank you for your feedback. It seems to be caused by [this commit](https://github.com/qchenqizhi/QCropper/commit/214ebc681ad2d67b7b342dc11f90aad8898f632a). If you do not need to crop the transparent image, you can remove this modification first. The specific reason may be a bug in the creation method of CGContext. I need to research.

**Comment by qchenqizhi** [comment] 2021-03-10 06:31
It has been fixed by [this commit](https://github.com/qchenqizhi/QCropper/commit/f83752866be363d989e5076c394de6a876c1d00e), please check, learn from [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m)

**Closed as completed** 2021-03-15 00:37 UTC
Labels: bug
